# Generated by Django 3.2.5 on 2021-08-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
